### ISSUE TITLE
[Feature (or bug fix?)] Trigger weapon targets on first pickup in Co-op

### ISSUE THREAD

**Issue by 4LT** [quake-mapping-community/smp#1]
Hey DT, I thought of this while I was watching you and ArrCee playing the q25-limits jam.

## The problem ##
In vanilla progs, when picking up a weapon in co-op, the weapon's target is never triggered, and the weapon remains in place.  This contrasts with the behavior in singleplayer, where picking up a weapon will cause it to disappear and trigger its target.

## Proposed Solution ##
Have the weapon trigger its target on touch, but **only** when touched for the first time, and otherwise leave the behavior the same.  This will cause co-op behavior to mimic singleplayer behavior of weapon pickups while retaining the weapon on pickup so other players can pick up the weapon.

**Comment by dumptruckDS** [comment]
This is already fixed in progs_dump IIRC. I will look into adding it to smp but I did not code that functionality so I'll need to review how it will integrate here.

**Comment by dumptruckDS** [comment]
This is still on my radar. The latest version needed to be completed for a speed mapping event.

**Comment by dumptruckDS** [comment]
Fixed in 2021.10
